chore(aws-quota): hack to avoid the aws cloudtrail quota

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -211,6 +211,20 @@ jobs:
       if: ${{ inputs.test_type != '' }}
       run: docker pull $IMAGE_NAME
 
+    - name: Check AWS Quota
+      run: |
+        attempts=0
+        until make check_aws_quota; do
+          if [ $attempts -ge 10 ]; then
+            echo "Exceeded maximum retries for quota check."
+            exit 1
+          fi
+          echo "Failed to meet quota. Retrying in 2 minutes..."
+          sleep 120
+          attempts=$((attempts + 1))
+        done
+    
+
     - name: Setup Infra and Run spec tests
       run: make docker/test
       env:
